name: "Pull Request Labeler"
on: [pull_request_target]

jobs:
  set-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: '.github/action_configs/labeler.yml'
          sync-labels: true
      - name: Add release label
        uses: actions/github-script@v6
        if: ${{ contains(github.event.pull_request.base.ref, 'release_v') }}
        with:
          github-token: ${{ secrets.ADD_LABELS_WITH_REST_API }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["release_target"]
            })
